- name: install maven
  ansible.builtin.yum:
    name: maven
    state: present

- name: Add user
  ansible.builtin.user:
    name: roboshop

- name: download code
  include_role:
    name: common
    tasks_from: download

- name: removing old code
  ansible.builtin.file:
    path: /home/roboshop/{{component}}
    state: absent

- name: copy application code
  ansible.builtin.copy:
    src: /tmp/{{component}}-main/
    dest: /home/roboshop/{{component}}
    remote_src: true
  become_user: roboshop

- name: make maven package
  ansible.builtin.shell:
    cmd: mvn clean package && target/shipping-1.0.jar shipping.jar
    chdir: /home/roboshop/{{component}}
  become_user: roboshop
  ignore_errors: yes

- name: update systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{component}}.service

- name: start service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

