- name: install maven
  ansible.builtin.yum:
    name: maven
    state: present

- name: Add user
  ansible.builtin.user:
    name: roboshop

- name: download code
  include_role:
    name: common
    tasks_from: download

- name: make maven package
  ansible.builtin.shell:
    chdir: /home/roboshop/shipping
    cmd: mvn clean package && target/shipping-1.0.jar shipping.jar


- name: update systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{component}}.service

- name: start service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

