- name: setup frontend
  hosts: frontend
  become: true
  tags: frontend
  roles:
    - frontend

- name: setup mangoDB
  hosts: mongodb
  become: true
  tags: mongodb
  roles:
    - mongodb

- name: setup catalogue
  hosts: catalogue
  become: true
  tags: catalogue
  roles:
    - catalogue