- name: install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name: add user
  ansible.builtin.user:
    name: roboshop
  register: USER_INFO


- name: download code
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: removing old code
  ansible.builtin.file:
    path: /home/roboshop/{{component}}
    state: absent

- name: copy application code
  ansible.builtin.copy:
    src: /tmp/{{component}}-main/
    dest: /home/roboshop/{{component}}
    remote_src: true
  become_user: roboshop


- name: Install specified python requirements
  pip:
    requirements: /home/roboshop/{{component}}/requirements.txt
    executable: pip3

- name: change user id
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{component}}/{{component}}.ini
    regexp: '^uid'
    line: uid = {{USER_INFO.uid}}

- name: change user group
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{component}}/{{component}}.ini
    regexp: '^gid'
    line: gid = {{USER_INFO.group}}

- name: update systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{component}}.service

- name: start payment service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: started
    enabled: yes
    daemon_reload: yes
