- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: install aws cli
  ansible.builtin.yum:
    name: python
    present: present

- name: Unarchive a aws zip file
  ansible.builtin.unarchive:
    src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
    dest: /tmp
    remote_src: yes

#- name: run shell command to get aws version
#  ansible.builtin.shell:
#    cmd: aws --version
#  register: AWS_VERSION
#
#- name: print version aws installed
#  ansible.builtin.debug:
#    msg: "{{AWS_VERSION}}"
#
#- name: replace access id and key
#  ansible.builtin.lineinfile:
#    path: ~/.aws/credentials
#    regexp: '^aws_access_key_id'
#    line: aws_access_key_id = {{aws_access_key_id}}
#
#- name: replace access id and key
#  ansible.builtin.lineinfile:
#    path: ~/.aws/credentials
#    regexp: '^aws_secret_access_key'
#    line: aws_secret_access_key = {{aws_secret_access_key}}
#
#- name: replace access id and key
#  ansible.builtin.lineinfile:
#    path: ~/.aws/config
#    regexp: '^region'
#    line: region = {{region}}
#

